language: node_js
node_js:
  - "12.12.0"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run test
  - npm run lint
  - npm run compile
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
